WITH votos AS (
    SELECT 
        NM_VOTAVEL, 
        DS_CARGO,
        NR_ZONA, 
        NR_SECAO, 
        SUM(QT_VOTOS) AS QT_VOTOS
    FROM deputados
    WHERE NR_ZONA IN (29, 96)
    AND NM_VOTAVEL IN (
        -- Lista de deputados federais e estaduais
        'ALESSANDRA HABER CARVALHO SANTOS',
        'EDER MAURO CARDOSO BARRA',
        'ELCIONE THEREZINHA ZAHLUTH BARBALHO',
        'JOSE BENITO PRIANTE JUNIOR',
        'RENILCE CONCEIÇÃO NICODEMOS DE ALBUQUERQUE',
        'JOÃO FERRARI JÚNIOR',
        'DILVANDA FURTADO FARO',
        'CELSO SABINO DE OLIVEIRA',
        'ANTONIO LEOCADIO DOS SANTOS',
        'KENISTON DE JESUS REGO BRAGA',
        'ANDREIA BRITO GONÇALVES SIQUEIRA',
        'JOAQUIM PASSARINHO PINTO DE SOUZA PORTO',
        'LENILDO MENDES DOS SANTOS SERTÃO',
        'OLIVAL HENRIQUE MARQUES DE SOUZA',
        'AIRTON LUIZ FALEIRO',
        'HENDERSON LIRA PINTO',
        'RAIMUNDO JOSE PEREIRA DOS SANTOS',
        'MARCO ADRIANO ALBUQUERQUE COELHO',
        'ANA MARIA DO SOCORRO MAGNO CUNHA',
        'ANDREIA SERRA MELO',
        'ANGELO AUGUSTO DE OLIVEIRA FERRARI',
        'AVEILTON SILVA DE SOUZA',
        'ANTONIO GOMES DE LIMA',
        'FLAVIO HIGOR PANTOJA',
        'IVANALDO BRAZ SILVA SIMPLÍCIO',
        'CARLOS ALBERTO BARROS BORDALO',
        'CARLOS VINICIOS DE MELO VIEIRA',
        'WENDERSON AZEVEDO CHAMON',
        'FRANCISCO DAS CHAGAS SILVA MELO FILHO',
        'CILENE LISBOA COUTO MARQUES',
        'NEIL DUARTE DE SOUZA',
        'NILTON SILVA DAS NEVES',
        'ANTONIA DIANA MOTA DE OLIVEIRA',
        'DIRCEU TEN CATEN PIES',
        'WANDERLAN AUGUSTO BRANDAO QUARESMA',
        'ELIAS GUIMARÃES SANTIAGO',
        'ELIEL PEREIRA FAUSTINO FILHO',
        'ERALDO SORGE SEBASTIAO PIMENTA',
        'ERICK DA COSTA MONTEIRO',
        'FABIO DE MELO FIGUEIRAS',
        'FÁBIO SOUSA DE FREITAS',
        'GUSTAVO BEMERGUY SEFER',
        'IRAN ATAIDE DE LIMA',
        'JOÃO DE NAZARÉ PINGARILHO NETO',
        'JOSUÉ VIEIRA DE ABREU',
        'LÍVIA DUARTE PUTY',
        'JOSE LUCIO OGAWA RODRIGUES',
        'LUIZ FURTADO REBELO FILHO',
        'MARIA DO CARMO MARTINS LIMA',
        'MARTINHO ARNALDO CAMPOS CARMONA',
        'PAULA CRISTINA TITAN REBELLO',
        'RENATO PAIVA DE OLIVEIRA',
        'HUGO ROGERIO SARMANHO BARRA',
        'RONIE RUFINO DA SILVA',
        'THIAGO ARAÚJO',
        'FRANCISCO TORRES DE PAULA FILHO',
        'WESCLEY SILVA AGUIAR',
        'JOSE WILSON COSTA ARAUJO'
    )
    GROUP BY NM_VOTAVEL, DS_CARGO, NR_ZONA, NR_SECAO
),
soma_votos AS (
    SELECT 
        NM_VOTAVEL, 
        DS_CARGO,
        NR_ZONA, 
        SUM(QT_VOTOS) AS TOTAL_VOTOS
    FROM votos
    GROUP BY NM_VOTAVEL, DS_CARGO, NR_ZONA
),
max_secao AS (
    SELECT 
        NM_VOTAVEL, 
        CONCAT(NR_SECAO, ' - ', QT_VOTOS) AS SECAO_MAX_VOTOS
    FROM votos v1
    WHERE QT_VOTOS = (
        SELECT MAX(QT_VOTOS) 
        FROM votos v2 
        WHERE v1.NM_VOTAVEL = v2.NM_VOTAVEL
    )
)
SELECT 
    s.NM_VOTAVEL AS Nome,
    s.DS_CARGO AS Cargo,
    COALESCE(MAX(CASE WHEN s.NR_ZONA = 29 THEN s.TOTAL_VOTOS END), 0) AS "Zona 29",
    COALESCE(MAX(CASE WHEN s.NR_ZONA = 96 THEN s.TOTAL_VOTOS END), 0) AS "Zona 96",
    MAX(m.SECAO_MAX_VOTOS) AS "Seção com mais votos"
FROM soma_votos s
LEFT JOIN max_secao m 
    ON s.NM_VOTAVEL = m.NM_VOTAVEL
GROUP BY s.NM_VOTAVEL, s.DS_CARGO
ORDER BY s.NM_VOTAVEL;
